sudo: required

language: python

services:
  - docker

before_install:
  - docker --version
  - pip install docker-compose
  - docker-compose -v
  - export USER_ID=$UID
  - export JENKINS_PASSWORD=*****

install:
  - ./rename.py travis
  - ./sslcert jenkins/sslcert localhost
  - ./sslcert nginx/sslcert localhost
  - cat docker-compose.yml
  - docker-compose -f docker-compose.yml build

script:
  - ./runtest.sh
